// <auto-generated />
using System;
using GiftExchange.Data.GiftExchangeDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GiftExchange.Data.Migrations
{
    [DbContext(typeof(GiftExchangeContext))]
    [Migration("20240814172727_CreateSeedData")]
    partial class CreateSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GiftExchange.Data.GiftExchangeDb.Schema.Exchange", b =>
                {
                    b.Property<int>("ExchangeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExchangeId"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)");

                    b.Property<Guid>("ExchangeIdentifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int>("MaxSwipes")
                        .HasColumnType("int");

                    b.Property<int>("MaxTurnActions")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ExchangeId");

                    b.ToTable("Exchanges", "GiftExchange");
                });

            modelBuilder.Entity("GiftExchange.Data.GiftExchangeDb.Schema.Gift", b =>
                {
                    b.Property<int>("GiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GiftId"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<int>("ExchangeId")
                        .HasColumnType("int");

                    b.Property<Guid>("GiftIdentifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<bool>("HasLotteryTickets")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("GiftId");

                    b.HasIndex("ExchangeId");

                    b.ToTable("Gifts", "GiftExchange");
                });

            modelBuilder.Entity("GiftExchange.Data.GiftExchangeDb.Schema.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerId"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExchangeId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("PlayerIdentifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.HasKey("PlayerId");

                    b.HasIndex("ExchangeId");

                    b.ToTable("Players", "GiftExchange");
                });

            modelBuilder.Entity("GiftExchange.Data.GiftExchangeDb.Schema.Turn", b =>
                {
                    b.Property<int>("TurnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TurnId"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExchangeId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StartingPlayerId")
                        .HasColumnType("int");

                    b.Property<Guid>("TurnIdentifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int>("TurnNumber")
                        .HasColumnType("int");

                    b.Property<int>("TurnStatusId")
                        .HasColumnType("int");

                    b.HasKey("TurnId");

                    b.HasIndex("ExchangeId");

                    b.HasIndex("StartingPlayerId");

                    b.HasIndex("TurnStatusId");

                    b.ToTable("Turns", "GiftExchange");
                });

            modelBuilder.Entity("GiftExchange.Data.GiftExchangeDb.Schema.TurnAction", b =>
                {
                    b.Property<int>("TurnActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TurnActionId"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GiftId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ParentTurnActionId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<Guid>("TurnActionIdentifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int>("TurnActionTypeId")
                        .HasColumnType("int");

                    b.Property<int>("TurnId")
                        .HasColumnType("int");

                    b.HasKey("TurnActionId");

                    b.HasIndex("GiftId");

                    b.HasIndex("ParentTurnActionId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TurnActionTypeId");

                    b.HasIndex("TurnId");

                    b.ToTable("TurnActions", "GiftExchange");
                });

            modelBuilder.Entity("GiftExchange.Data.GiftExchangeDb.Schema.TurnActionType", b =>
                {
                    b.Property<int>("TurnActionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TurnActionTypeId"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TurnActionTypeId");

                    b.ToTable("TurnActionTypes", "GiftExchange");

                    b.HasData(
                        new
                        {
                            TurnActionTypeId = 10,
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2024, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "SeedData",
                            ModifiedDate = new DateTime(2024, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "New"
                        },
                        new
                        {
                            TurnActionTypeId = 20,
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2024, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "SeedData",
                            ModifiedDate = new DateTime(2024, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Trade"
                        });
                });

            modelBuilder.Entity("GiftExchange.Data.GiftExchangeDb.Schema.TurnStatus", b =>
                {
                    b.Property<int>("TurnStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TurnStatusId"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TurnStatusId");

                    b.ToTable("TurnStatuses", "GiftExchange");

                    b.HasData(
                        new
                        {
                            TurnStatusId = 1,
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2024, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "SeedData",
                            ModifiedDate = new DateTime(2024, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "NotPlayed"
                        },
                        new
                        {
                            TurnStatusId = 2,
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2024, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "SeedData",
                            ModifiedDate = new DateTime(2024, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "InProgress"
                        },
                        new
                        {
                            TurnStatusId = 3,
                            CreatedBy = "SeedData",
                            CreatedDate = new DateTime(2024, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "SeedData",
                            ModifiedDate = new DateTime(2024, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Completed"
                        });
                });

            modelBuilder.Entity("GiftExchange.Data.GiftExchangeDb.Schema.Gift", b =>
                {
                    b.HasOne("GiftExchange.Data.GiftExchangeDb.Schema.Exchange", "Exchange")
                        .WithMany("Gifts")
                        .HasForeignKey("ExchangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exchange");
                });

            modelBuilder.Entity("GiftExchange.Data.GiftExchangeDb.Schema.Player", b =>
                {
                    b.HasOne("GiftExchange.Data.GiftExchangeDb.Schema.Exchange", "Exchange")
                        .WithMany("Players")
                        .HasForeignKey("ExchangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exchange");
                });

            modelBuilder.Entity("GiftExchange.Data.GiftExchangeDb.Schema.Turn", b =>
                {
                    b.HasOne("GiftExchange.Data.GiftExchangeDb.Schema.Exchange", "Exchange")
                        .WithMany("Turns")
                        .HasForeignKey("ExchangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GiftExchange.Data.GiftExchangeDb.Schema.Player", "StartingPlayer")
                        .WithMany()
                        .HasForeignKey("StartingPlayerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GiftExchange.Data.GiftExchangeDb.Schema.TurnStatus", "TurnStatus")
                        .WithMany()
                        .HasForeignKey("TurnStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exchange");

                    b.Navigation("StartingPlayer");

                    b.Navigation("TurnStatus");
                });

            modelBuilder.Entity("GiftExchange.Data.GiftExchangeDb.Schema.TurnAction", b =>
                {
                    b.HasOne("GiftExchange.Data.GiftExchangeDb.Schema.Gift", "Gift")
                        .WithMany()
                        .HasForeignKey("GiftId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GiftExchange.Data.GiftExchangeDb.Schema.TurnAction", "ParentTurnAction")
                        .WithMany()
                        .HasForeignKey("ParentTurnActionId");

                    b.HasOne("GiftExchange.Data.GiftExchangeDb.Schema.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GiftExchange.Data.GiftExchangeDb.Schema.TurnActionType", "TurnActionType")
                        .WithMany()
                        .HasForeignKey("TurnActionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GiftExchange.Data.GiftExchangeDb.Schema.Turn", "Turn")
                        .WithMany("TurnActions")
                        .HasForeignKey("TurnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gift");

                    b.Navigation("ParentTurnAction");

                    b.Navigation("Player");

                    b.Navigation("Turn");

                    b.Navigation("TurnActionType");
                });

            modelBuilder.Entity("GiftExchange.Data.GiftExchangeDb.Schema.Exchange", b =>
                {
                    b.Navigation("Gifts");

                    b.Navigation("Players");

                    b.Navigation("Turns");
                });

            modelBuilder.Entity("GiftExchange.Data.GiftExchangeDb.Schema.Turn", b =>
                {
                    b.Navigation("TurnActions");
                });
#pragma warning restore 612, 618
        }
    }
}
